.TH ladvd 8 "Juli 27 2008" ladvd
.SH NAME
ladvd \- send link layer advertisements
.SH SYNOPSIS
.BI "ladvd [ -c ] [ -l ]" 
.BI "[ " INTERFACE " ] [ " INTERFACE " ]"
.B ...
.SH DESCRIPTION
.B ladvd
sends CDP/LLDP link layer advertisements on all available
interfaces. This makes connected hosts visible on managed
switches. By default it will run as a non-privileged user and daemonize.
Either -c or -l is required. Optionally a list of interfaces on which ladvd
should transmit can be supplied.
.SH OPTIONS
.IP -c
Send CDP messages.
.IP -l
Send LLDP messages.
.IP -f
Run in the foreground and send logging to stderr.
.IP -o
Run only once, useful for quick troubleshooting.
.IP "-u user"
Switch to this user (defaults to nobody).
.IP "-L <location>"
Specify the physical location of the server.
.IP -v
Increase logging verbosity.
.IP -d
Dump packets to stdout.
.SH AUTHOR
Sten Spans <sten@blinkenlights.nl>
