#!/bin/sh 

set -e

if [ "$1" = "configure" ]; then
    if ! getent passwd ladvd >/dev/null; then
	adduser --system --quiet --group --no-create-home \
	    --disabled-password --disabled-login ladvd || :
    fi
fi

#DEBHELPER#

